name = "webauthn-auth-server"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database binding
# After creating database with: wrangler d1 create webauthn-db
# Add the database_id from the output
[[d1_databases]]
binding = "DB"
database_name = "webauthn-db"
database_id = "YOUR_DATABASE_ID_HERE"  # Replace with actual ID from wrangler d1 create

# R2 Bucket binding
# After creating bucket with: wrangler r2 bucket create webauthn-blobs
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "webauthn-blobs"

[build]
command = "bun run build"
